"""
Static HTML Generator for Validation Results

Creates self-contained HTML files with embedded table data, CSS, and JavaScript.
These files can be viewed offline and include SEO metadata (JSON-LD and hidden text).

Supports multiple JSON-LD schema types:
- Dataset (default for table results)
- SoftwareApplication (for product pages)
- FAQPage (for FAQ content)

Usage:
    from interface_lambda.utils.static_html_generator import StaticHTMLGenerator

    generator = StaticHTMLGenerator()
    html = generator.generate(
        table_metadata=metadata,
        title="My Table",
        subtitle="Generated 2024-01-15",
        description="Validation results for My Table",
        seo_content="Additional keywords for search engines",
        interactive_url="https://hyperplexity.com?mode=viewer&session=xxx",
        faqs=[
            {"question": "How does this work?", "answer": "It validates data..."},
        ]
    )
"""
import json
import os
import logging
from datetime import datetime
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


# Default FAQs for validation exports (used when no FAQs are provided)
DEFAULT_VALIDATION_FAQS = [
    {
        "question": "What is this validation table?",
        "answer": "This table was generated by Hyperplexity, an AI-powered research validation platform. Each cell contains data validated against multiple web sources, with confidence scores indicating reliability."
    },
    {
        "question": "What do the confidence colors mean?",
        "answer": "Green (high confidence) means the data is well-supported by multiple sources. Yellow (medium confidence) indicates partial support or fewer sources. Red (low confidence) suggests limited or conflicting evidence. Blue indicates identifier columns."
    },
    {
        "question": "How can I verify the sources?",
        "answer": "Click any cell to see the full value and supporting citations. Each citation includes a link to the original source so you can verify the information yourself."
    },
    {
        "question": "How is this different from ChatGPT or other AI tools?",
        "answer": "Unlike general AI assistants that can hallucinate information, Hyperplexity validates every data point against real web sources and provides citations. The confidence scoring helps you identify which data points are most reliable."
    },
    {
        "question": "Can I use this data in my research?",
        "answer": "Yes, but always verify important data points using the provided citations. This table is a research aid, not a primary source. Check the original sources for critical decisions."
    },
    {
        "question": "How often is this data updated?",
        "answer": "This is a static snapshot from the validation date shown. For the most current data, visit Hyperplexity.AI to run a fresh validation against current web sources."
    }
]

# Organization schema - reused across all pages
ORGANIZATION_SCHEMA = {
    "@type": "Organization",
    "name": "Eliyahu.AI",
    "url": "https://eliyahu.ai",
    "logo": "https://eliyahu.ai/logo.png",
    "sameAs": [
        "https://www.linkedin.com/company/eliyahu-ai"
    ]
}


class StaticHTMLGenerator:
    """Generates standalone HTML files for validation results with SEO optimization."""

    def __init__(self):
        self._template_cache = None
        self._css_cache = {}
        self._js_cache = None
        self._competitive_data_cache = None

    def get_competitive_data(self) -> Optional[Dict[str, Any]]:
        """
        Load competitive intelligence data from bundled templates.
        Returns cached data on subsequent calls.
        """
        if self._competitive_data_cache is not None:
            return self._competitive_data_cache

        json_paths = [
            os.path.join(os.path.dirname(__file__), '..', 'templates', 'seo', 'HyperplexityVsCompetition.json'),
            os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', '..',
                        'frontend', 'HyperplexityVsCompetition_20260130.json'),
        ]

        for json_path in json_paths:
            try:
                if os.path.exists(json_path):
                    with open(json_path, 'r', encoding='utf-8') as f:
                        self._competitive_data_cache = json.load(f)
                        logger.info(f"[STATIC_HTML] Loaded competitive SEO data from {json_path}")
                        return self._competitive_data_cache
            except Exception as e:
                logger.warning(f"[STATIC_HTML] Could not load competitive data from {json_path}: {e}")

        logger.warning("[STATIC_HTML] No competitive SEO data found")
        self._competitive_data_cache = {}  # Cache empty result to avoid repeated lookups
        return None

    @staticmethod
    def hash_string(s: str) -> int:
        """
        Deterministic hash function for module rotation.
        Based on FNV-1a hash algorithm - produces consistent results across runs.
        Use this to select content variants based on slug/URL.
        """
        h = 2166136261
        for char in s:
            h = h ^ ord(char)
            h = (h * 16777619) & 0xFFFFFFFF
        return h

    @staticmethod
    def pick_variant(variants: List[Any], seed: int, offset: int = 0) -> Any:
        """
        Deterministically pick a variant from a list based on seed.

        Args:
            variants: List of content variants
            seed: Hash seed (e.g., from hash_string)
            offset: Offset for picking different variants with same seed

        Returns:
            Selected variant
        """
        if not variants:
            return None
        return variants[(seed + offset) % len(variants)]

    def generate(
        self,
        table_metadata: Dict[str, Any],
        title: str,
        subtitle: str = "",
        description: str = "",
        seo_content: str = "",
        interactive_url: str = "",
        faqs: Optional[List[Dict[str, str]]] = None,
        schema_type: str = "Dataset",
        last_updated: Optional[str] = None,
        methodology: Optional[str] = None,
        slug: Optional[str] = None,
        competitive_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate a complete standalone HTML file with SEO optimization.

        Args:
            table_metadata: The table_metadata.json content
            title: Page title (also used in <h1>)
            subtitle: Subtitle text (shown below title)
            description: Meta description for SEO (max 160 chars recommended)
            seo_content: Hidden SEO content (accessible to crawlers) - legacy param
            interactive_url: Link to interactive version
            faqs: List of FAQ dicts with 'question' and 'answer' keys
            schema_type: JSON-LD schema type ('Dataset', 'SoftwareApplication', 'FAQPage')
            last_updated: ISO date string for freshness signals
            methodology: Short methodology description for verification context
            slug: URL slug for deterministic content rotation
            competitive_data: Competitive intelligence JSON for rich SEO content

        Returns:
            Complete HTML string ready to save to file
        """
        # Load template and assets
        template = self._get_template()
        table_css = self._get_css()
        table_js = self._get_js()

        # Auto-generate methodology from table metadata if not provided
        if not methodology:
            rows = table_metadata.get('rows', [])
            columns = table_metadata.get('columns', [])
            methodology = f"Validated {len(rows)} entities across {len(columns)} research dimensions with web-sourced citations and confidence scoring."

        # Auto-generate last_updated if not provided
        if not last_updated:
            last_updated = datetime.utcnow().strftime("%Y-%m-%d")

        # Auto-get FAQs from SEO extractor if not provided and competitive data available
        if not faqs and competitive_data:
            try:
                from interface_lambda.utils.seo_content_extractor import SEOContentExtractor
                extractor = SEOContentExtractor(competitive_data)
                faqs = extractor.get_faqs(slug or title, count=6)
            except Exception as e:
                logger.debug(f"[STATIC_HTML] Could not auto-load FAQs: {e}")

        # Use default validation FAQs if still no FAQs
        if not faqs:
            faqs = DEFAULT_VALIDATION_FAQS

        # Generate JSON-LD structured data (can include multiple schemas)
        json_ld_blocks = self._generate_json_ld_blocks(
            title=title,
            description=description,
            table_metadata=table_metadata,
            schema_type=schema_type,
            faqs=faqs,
            interactive_url=interactive_url
        )

        # Generate footer link if interactive URL provided
        footer_link = ""
        if interactive_url:
            footer_link = f' | <a href="{self._escape_html(interactive_url)}" target="_blank" rel="noopener">View Interactive Version</a>'

        # Generate methodology block (auto-generated above if not provided)
        methodology_html = self._generate_methodology_block(
            methodology=methodology,
            last_updated=last_updated
        )

        # Generate FAQ HTML (visible accordion - required by Google for FAQ rich snippets)
        faq_html = ""
        if faqs:
            faq_html = self._generate_faq_html(faqs)

        # Generate rich SEO content from competitive data
        seo_layer_html = self._generate_seo_layer(
            slug=slug or title,
            competitive_data=competitive_data,
            legacy_content=seo_content
        )

        # Build the HTML by replacing placeholders
        html = template
        html = html.replace('{{TITLE}}', self._escape_html(title))
        html = html.replace('{{SUBTITLE}}', self._escape_html(subtitle))
        html = html.replace('{{DESCRIPTION}}', self._escape_html(
            self._truncate_description(description or f"Validation results for {title}")
        ))
        html = html.replace('{{TABLE_CSS}}', table_css)
        html = html.replace('{{TABLE_JS}}', table_js)
        html = html.replace('{{METADATA_JSON}}', json.dumps(table_metadata))
        html = html.replace('{{JSON_LD}}', json_ld_blocks)
        html = html.replace('{{SEO_CONTENT}}', seo_layer_html)
        html = html.replace('{{FOOTER_LINK}}', footer_link)
        html = html.replace('{{METHODOLOGY_BLOCK}}', methodology_html)
        html = html.replace('{{FAQ_BLOCK}}', faq_html)

        return html

    def _generate_seo_layer(
        self,
        slug: str,
        competitive_data: Optional[Dict[str, Any]] = None,
        legacy_content: str = ""
    ) -> str:
        """
        Generate hidden SEO content layer with rich marketing content.

        Uses clip-path technique to render content that's accessible to
        crawlers but not visible to users.

        Args:
            slug: Page identifier for deterministic content rotation
            competitive_data: Competitive intelligence JSON
            legacy_content: Legacy seo_content string (fallback)

        Returns:
            HTML string for the SEO layer
        """
        # If no competitive data, fall back to legacy content
        if not competitive_data:
            if legacy_content:
                return legacy_content
            return ""

        try:
            from interface_lambda.utils.seo_content_extractor import SEOContentExtractor

            extractor = SEOContentExtractor(competitive_data)
            seo_html = extractor.render_seo_html(
                slug=slug,
                include_hero=True,
                paragraph_count=3,
                comparison_count=2
            )

            # Combine with any legacy content
            if legacy_content:
                seo_html = f"{seo_html}\n<div class='seo-legacy'>{self._escape_html(legacy_content)}</div>"

            return seo_html

        except Exception as e:
            logger.warning(f"[STATIC_HTML] Failed to generate SEO layer: {e}")
            return legacy_content if legacy_content else ""

    def _truncate_description(self, desc: str, max_length: int = 160) -> str:
        """Truncate description to recommended SEO length."""
        if len(desc) <= max_length:
            return desc
        return desc[:max_length - 3].rsplit(' ', 1)[0] + '...'

    def _generate_json_ld_blocks(
        self,
        title: str,
        description: str,
        table_metadata: Dict[str, Any],
        schema_type: str,
        faqs: Optional[List[Dict[str, str]]],
        interactive_url: str
    ) -> str:
        """Generate all JSON-LD schema blocks as a single string."""
        schemas = []

        # Main schema based on type
        if schema_type == "Dataset":
            schemas.append(self._generate_dataset_schema(title, description, table_metadata))
        elif schema_type == "SoftwareApplication":
            schemas.append(self._generate_software_schema(title, description, interactive_url))

        # Add FAQ schema if FAQs provided (in addition to main schema)
        if faqs:
            schemas.append(self._generate_faq_schema(faqs))

        # Combine all schemas
        return "\n    ".join(
            f'<script type="application/ld+json">\n{json.dumps(schema, indent=2)}\n    </script>'
            for schema in schemas
        )

    def _generate_dataset_schema(
        self,
        title: str,
        description: str,
        table_metadata: Dict[str, Any]
    ) -> Dict:
        """Generate JSON-LD Dataset schema for table results."""
        rows = table_metadata.get('rows', [])
        columns = table_metadata.get('columns', [])
        column_names = [col.get('name', '') for col in columns if col.get('name')]

        return {
            "@context": "https://schema.org",
            "@type": "Dataset",
            "name": title,
            "description": description or f"Research data table with {len(rows)} rows and {len(columns)} columns, validated with citations and confidence scoring.",
            "creator": ORGANIZATION_SCHEMA,
            "dateCreated": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "variableMeasured": column_names[:20],
            "distribution": {
                "@type": "DataDownload",
                "encodingFormat": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "contentUrl": "#download"
            }
        }

    def _generate_software_schema(
        self,
        title: str,
        description: str,
        url: str
    ) -> Dict:
        """Generate JSON-LD SoftwareApplication schema for product pages."""
        return {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "@id": f"{url}#software" if url else None,
            "name": title,
            "operatingSystem": "Web",
            "applicationCategory": "BusinessApplication",
            "url": url or "https://eliyahu.ai/hyperplexity",
            "description": description or "Generates, validates, and updates research matrices (tables) with citations and confidence scoring.",
            "provider": ORGANIZATION_SCHEMA,
            "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD",
                "description": "Pay-per-use pricing"
            }
        }

    def _generate_faq_schema(self, faqs: List[Dict[str, str]]) -> Dict:
        """Generate JSON-LD FAQPage schema. FAQs must be visible on page."""
        return {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": faq.get('question', ''),
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": faq.get('answer', '')
                    }
                }
                for faq in faqs if faq.get('question') and faq.get('answer')
            ]
        }

    def _generate_methodology_block(self, methodology: str, last_updated: str) -> str:
        """Generate visible methodology/freshness block for verification context."""
        parts = []
        if last_updated:
            parts.append(f'<span class="last-updated">Last updated: {self._escape_html(last_updated)}</span>')
        if methodology:
            parts.append(f'<span class="methodology">{self._escape_html(methodology)}</span>')

        if not parts:
            return ""

        return f'''
        <div class="methodology-block">
            {" | ".join(parts)}
        </div>
        '''

    def _generate_faq_html(self, faqs: List[Dict[str, str]]) -> str:
        """
        Generate collapsible FAQ HTML section.
        Google requires FAQ content to be visible on page (accordions OK).
        FAQ is collapsed by default to keep focus on the table.
        """
        if not faqs:
            return ""

        faq_items = []
        for i, faq in enumerate(faqs):
            question = self._escape_html(faq.get('question', ''))
            answer = self._escape_html(faq.get('answer', ''))
            if question and answer:
                faq_items.append(f'''
                <details class="faq-item">
                    <summary class="faq-question">{question}</summary>
                    <div class="faq-answer">{answer}</div>
                </details>
                ''')

        if not faq_items:
            return ""

        return f'''
        <div class="faq-section collapsed" id="faq-section">
            <div class="faq-toggle" onclick="document.getElementById('faq-section').classList.toggle('collapsed')">
                <h2 class="faq-title">Frequently Asked Questions</h2>
                <span class="faq-toggle-icon">▼</span>
            </div>
            <div class="faq-content">
                {"".join(faq_items)}
            </div>
        </div>
        '''

    def _get_template(self) -> str:
        """Load the HTML template."""
        if self._template_cache:
            return self._template_cache

        # Try loading from bundled templates directory
        template_paths = [
            os.path.join(os.path.dirname(__file__), '..', 'templates', 'standalone-table-template.html'),
            os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', '..',
                        'frontend', 'src', 'standalone-table-template.html'),
        ]

        for template_path in template_paths:
            try:
                if os.path.exists(template_path):
                    with open(template_path, 'r', encoding='utf-8') as f:
                        self._template_cache = f.read()
                        logger.info(f"[STATIC_HTML] Loaded template from {template_path}")
                        return self._template_cache
            except Exception as e:
                logger.warning(f"[STATIC_HTML] Could not load template from {template_path}: {e}")

        # Fallback to minimal embedded template
        logger.warning("[STATIC_HTML] Using minimal fallback template")
        self._template_cache = self._get_minimal_template()
        return self._template_cache

    def _get_css(self) -> str:
        """Load table CSS (07-tables.css)."""
        if 'table_css' in self._css_cache:
            return self._css_cache['table_css']

        css_paths = [
            os.path.join(os.path.dirname(__file__), '..', 'templates', 'css', '07-tables.css'),
            os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', '..',
                        'frontend', 'src', 'styles', '07-tables.css'),
        ]

        for css_path in css_paths:
            try:
                if os.path.exists(css_path):
                    with open(css_path, 'r', encoding='utf-8') as f:
                        self._css_cache['table_css'] = f.read()
                        logger.info(f"[STATIC_HTML] Loaded CSS from {css_path}")
                        return self._css_cache['table_css']
            except Exception as e:
                logger.warning(f"[STATIC_HTML] Could not load CSS from {css_path}: {e}")

        # Fallback to minimal CSS
        logger.warning("[STATIC_HTML] Using minimal fallback CSS")
        self._css_cache['table_css'] = self._get_minimal_css()
        return self._css_cache['table_css']

    def _get_js(self) -> str:
        """Load interactive table JavaScript (16-interactive-table.js)."""
        if self._js_cache:
            return self._js_cache

        js_paths = [
            os.path.join(os.path.dirname(__file__), '..', 'templates', 'js', '16-interactive-table.js'),
            os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', '..',
                        'frontend', 'src', 'js', '16-interactive-table.js'),
        ]

        for js_path in js_paths:
            try:
                if os.path.exists(js_path):
                    with open(js_path, 'r', encoding='utf-8') as f:
                        self._js_cache = f.read()
                        logger.info(f"[STATIC_HTML] Loaded JS from {js_path}")
                        return self._js_cache
            except Exception as e:
                logger.warning(f"[STATIC_HTML] Could not load JS from {js_path}: {e}")

        # Fallback to error message
        logger.error("[STATIC_HTML] Could not load interactive table JS")
        self._js_cache = '/* Interactive table JS not found - table will not be interactive */'
        return self._js_cache

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters to prevent XSS."""
        if not text:
            return ''
        return (str(text)
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
            .replace("'", '&#39;'))

    def _get_minimal_template(self) -> str:
        """Return a minimal template if the full one isn't available."""
        return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}}</title>
    <meta name="description" content="{{DESCRIPTION}}">
    {{JSON_LD}}
    <style>
        :root {
            --font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            --border-radius: 8px;
            --font-size-base: 14px;
            --text-color: #333;
            --text-secondary: #666;
            --card-background: #fff;
            --primary-color: #28FF3A;
        }
        * { box-sizing: border-box; }
        body { font-family: var(--font-family); margin: 0; padding: 20px; background: #f5f5f5; color: var(--text-color); }
        .viewer-container { max-width: 1200px; margin: 0 auto; background: var(--card-background); border-radius: var(--border-radius); padding: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        .viewer-header { margin-bottom: 20px; padding-bottom: 15px; border-bottom: 1px solid #eee; }
        .viewer-title { margin: 0 0 5px 0; font-size: 1.5rem; font-weight: 600; }
        .viewer-subtitle { color: var(--text-secondary); margin: 0; }
        .viewer-footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; text-align: center; color: var(--text-secondary); font-size: 13px; }
        .viewer-footer a { color: var(--primary-color); text-decoration: none; }
        .seo-content { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); clip-path: inset(50%); white-space: nowrap; border: 0; }
        .seo-content .seo-hero h2 { font-size: 1.5rem; margin: 0 0 0.5rem 0; }
        .seo-content .seo-tagline { font-size: 1.1rem; margin: 0 0 1rem 0; }
        .seo-content .seo-feature { margin-bottom: 1rem; }
        .seo-content .seo-feature h3 { font-size: 1.1rem; margin: 0 0 0.5rem 0; }
        .seo-content .seo-comparison { margin-bottom: 1rem; }
        .seo-content .seo-comparison h3 { font-size: 1rem; margin: 0 0 0.5rem 0; }
        .methodology-block { font-size: 12px; color: var(--text-secondary); margin-bottom: 16px; padding: 8px 12px; background: #f8f9fa; border-radius: 4px; }
        .faq-section { margin-top: 32px; padding-top: 24px; border-top: 1px solid #eee; }
        .faq-section.collapsed .faq-content { display: none; }
        .faq-toggle { display: flex; align-items: center; justify-content: space-between; cursor: pointer; padding: 8px 0; }
        .faq-toggle:hover .faq-title { color: #28FF3A; }
        .faq-toggle-icon { font-size: 1.2rem; color: var(--text-secondary); transition: transform 0.2s ease; }
        .faq-section:not(.collapsed) .faq-toggle-icon { transform: rotate(180deg); }
        .faq-content { margin-top: 16px; }
        .faq-title { font-size: 1.25rem; margin: 0; }
        .faq-item { margin-bottom: 12px; border: 1px solid #e0e0e0; border-radius: 6px; }
        .faq-question { padding: 12px 16px; cursor: pointer; font-weight: 500; }
        .faq-question:hover { background: #f8f9fa; }
        .faq-answer { padding: 0 16px 12px 16px; color: var(--text-secondary); line-height: 1.6; }
        .generated-by { display: flex; align-items: center; justify-content: flex-end; gap: 6px; margin-bottom: 12px; font-size: 12px; color: var(--text-secondary); }
        .generated-by a { color: #28FF3A; text-decoration: none; font-weight: 500; }
        .generated-by a:hover { text-decoration: underline; }
        .generated-by-logo { height: 16px; width: auto; vertical-align: middle; }
        {{TABLE_CSS}}
    </style>
</head>
<body>
    <div class="seo-content" aria-hidden="true">{{SEO_CONTENT}}</div>
    <div class="viewer-container">
        <div class="viewer-header">
            <h1 class="viewer-title">{{TITLE}}</h1>
            <p class="viewer-subtitle">{{SUBTITLE}}</p>
        </div>
        {{METHODOLOGY_BLOCK}}
        <div class="generated-by">Generated by <a href="https://eliyahu.ai/hyperplexity" target="_blank" rel="noopener">Hyperplexity.AI</a></div>
        <div id="table-container"></div>
        {{FAQ_BLOCK}}
        <div class="viewer-footer">Generated by <a href="https://eliyahu.ai/hyperplexity" target="_blank">Hyperplexity</a>{{FOOTER_LINK}}</div>
    </div>
    <script>window.TABLE_METADATA={{METADATA_JSON}};</script>
    <script>
        {{TABLE_JS}}
        (function(){
            var c=document.getElementById('table-container');
            if(window.TABLE_METADATA && typeof InteractiveTable!=='undefined'){
                c.innerHTML=InteractiveTable.render(window.TABLE_METADATA,{showGeneralNotes:true,showLegend:true});
                InteractiveTable.init();
            } else {
                c.innerHTML='<p style="color:#666;text-align:center;">Table could not be rendered.</p>';
            }
        })();
    </script>
</body>
</html>'''

    def _get_minimal_css(self) -> str:
        """Return minimal CSS for basic table display."""
        return '''
/* Minimal table CSS fallback */
.interactive-table-container { overflow-x: auto; margin: 20px 0; }
.interactive-table { width: 100%; border-collapse: collapse; font-size: 14px; }
.interactive-table th, .interactive-table td { padding: 10px; border: 1px solid #e0e0e0; text-align: left; }
.interactive-table th { background: #f5f5f5; font-weight: 600; }
.interactive-table tr:hover { background: #f9f9f9; }
.confidence-high { background-color: rgba(40, 255, 58, 0.2); }
.confidence-medium { background-color: rgba(255, 235, 59, 0.2); }
.confidence-low { background-color: rgba(244, 67, 54, 0.2); }
.confidence-id { background-color: rgba(33, 150, 243, 0.2); }
.table-legend { display: flex; gap: 15px; margin-bottom: 15px; font-size: 13px; }
.legend-item { display: flex; align-items: center; gap: 5px; }
.legend-color { width: 16px; height: 16px; border-radius: 3px; }
.general-notes-box { background: #f0f7ff; border: 1px solid #cce5ff; border-radius: 8px; padding: 12px; margin-bottom: 15px; }
'''
