#!/usr/bin/env python3
"""
Transform static HTML viewer files to tight embedded format.

Removes header metadata, "Generated by" branding, FAQ section, and footer.
Optionally updates title/subtitle and increases title font size.

Usage:
    python transform_static_html.py input.html output.html --title "My Title" --subtitle "My Subtitle"
    python transform_static_html.py input.html output.html --remove-all-chrome
"""
import argparse
import re
import sys
from pathlib import Path


def transform_html(
    input_path: Path,
    output_path: Path,
    title: str = None,
    subtitle: str = None,
    remove_all_chrome: bool = False,
    increase_font: bool = True
):
    """
    Transform a static HTML file to tight embedded format.

    Args:
        input_path: Path to input HTML file
        output_path: Path to output HTML file
        title: New title (None = keep existing)
        subtitle: New subtitle (None = keep existing)
        remove_all_chrome: Remove title/subtitle too (overrides title/subtitle args)
        increase_font: Increase title font size from 1.5rem to 2rem
    """
    print(f"Reading {input_path}...")
    html = input_path.read_text(encoding='utf-8')

    # 1. Remove or replace header section
    if remove_all_chrome:
        # Remove entire viewer-header div
        html = re.sub(
            r'\s*<div class="viewer-header">.*?</div>\s*',
            '\n        ',
            html,
            flags=re.DOTALL
        )
        print("✓ Removed header (title/subtitle)")
    else:
        # Update title if provided
        if title:
            html = re.sub(
                r'<h1 class="viewer-title">.*?</h1>',
                f'<h1 class="viewer-title">{title}</h1>',
                html
            )
            print(f"✓ Updated title to: {title}")

        # Update subtitle if provided
        if subtitle:
            html = re.sub(
                r'<p class="viewer-subtitle">.*?</p>',
                f'<p class="viewer-subtitle">{subtitle}</p>',
                html
            )
            print(f"✓ Updated subtitle to: {subtitle}")

    # 2. Remove "Generated by Hyperplexity.AI" line
    html = re.sub(
        r'\s*<div class="generated-by">.*?</div>\s*',
        '\n        ',
        html,
        flags=re.DOTALL
    )
    print("✓ Removed 'Generated by' line")

    # 3. Remove FAQ section
    html = re.sub(
        r'\s*<div class="faq-section collapsed".*?</div>\s*(?=\s*<div|</div>)',
        '\n        ',
        html,
        flags=re.DOTALL
    )
    print("✓ Removed FAQ section")

    # 4. Remove footer
    html = re.sub(
        r'\s*<div class="viewer-footer">.*?</div>\s*',
        '\n        ',
        html,
        flags=re.DOTALL
    )
    print("✓ Removed footer")

    # 5. Remove empty methodology block if present
    html = re.sub(
        r'\s*<div class="methodology-block">.*?</div>\s*',
        '\n        ',
        html,
        flags=re.DOTALL
    )

    # 6. Increase title size
    if increase_font:
        html = re.sub(
            r'(\.viewer-title\s*\{[^}]*font-size:\s*)1\.5rem',
            r'\g<1>1.75rem',
            html
        )
        print("✓ Increased title size (1.5rem → 2rem)")

    # 7. Add infoBoxText to InteractiveTable.render call if missing
    # Check if it already has infoBoxText parameter
    if 'infoBoxText:' not in html:
        # Find the render call and add infoBoxText
        html = re.sub(
            r"(InteractiveTable\.render\(metadata,\s*\{[^}]*showLegend:\s*true)",
            r"\1,\n                        infoBoxText: 'Rows shown as columns. Color-coded by confidence. Hover for quick info, click for citations and details.'",
            html
        )
        print("✓ Added infoBoxText to render call")

    # 8. Ensure defaultOptions includes infoBoxText
    if 'infoBoxText: null' not in html:
        html = re.sub(
            r'(maxRows: null,\s*//[^\n]*\n\s*)\};',
            r"\1    infoBoxText: null,         // Blue info box text (shown after general notes)\n    };",
            html
        )
        print("✓ Added infoBoxText to defaultOptions")

    # 9. Ensure info box rendering code exists in the render function
    if 'opts.infoBoxText' not in html:
        # Insert info box rendering before legend
        html = re.sub(
            r'(\s*)(// Color legend/key)',
            r'\1// Blue info box (after general notes)\n\1if (opts.infoBoxText) {\n\1    html += `<div class="viewer-info-box">\n\1        <span class="viewer-info-icon">ℹ</span>\n\1        <span>${escapeHtml(opts.infoBoxText)}</span>\n\1    </div>`;\n\1}\n\n\1\2',
            html
        )
        print("✓ Added info box rendering code")

    # Write output
    print(f"Writing {output_path}...")
    output_path.write_text(html, encoding='utf-8')
    print(f"✅ Transformation complete!")


def main():
    parser = argparse.ArgumentParser(
        description='Transform static HTML viewer files to tight embedded format'
    )
    parser.add_argument('input', type=Path, help='Input HTML file')
    parser.add_argument('output', type=Path, help='Output HTML file')
    parser.add_argument('--title', help='New title text')
    parser.add_argument('--subtitle', help='New subtitle text')
    parser.add_argument('--remove-all-chrome', action='store_true',
                       help='Remove title, subtitle, and all branding')
    parser.add_argument('--no-font-increase', action='store_true',
                       help='Skip increasing title font size')

    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    transform_html(
        args.input,
        args.output,
        title=args.title,
        subtitle=args.subtitle,
        remove_all_chrome=args.remove_all_chrome,
        increase_font=not args.no_font_increase
    )


if __name__ == '__main__':
    main()
