@echo off
move test_config_lambda_save.py temp_unnecessary_files
move test_deployed_config_lambda.py temp_unnecessary_files
move test_download_bucket.py temp_unnecessary_files
move test_download_url_direct.py temp_unnecessary_files
move test_quick_features.py temp_unnecessary_files
move test_real_config_lambda.py temp_unnecessary_files
move test_schema_merge.py temp_unnecessary_files
move test_schema_validation.py temp_unnecessary_files
move test_validation.py temp_unnecessary_files
move test_validation_and_download.py temp_unnecessary_files 